[package]
name = "RustySnake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.25"
tokio = "1.21.0"
log = "0.4.17"
unicode-width = "0.1.9"
rand = "0.8.5"
argh = "0.1.8"